
SELECT * FROM EMPLOYEES e ;

SELECT * FROM TBLTODO t ;

INSERT INTO TBLTODO (SEQ, TITLE , ADDDATE, COMPLETEDATE)
		VALUES (21, '오라클 복습하기', SYSDATE, NULL);
	
SELECT * FROM TBLTODO t ;

INSERT INTO TBLTODO (SEQ, TITLE , ADDDATE, COMPLETEDATE)
		VALUES (23, 'HTML 복습하기', SYSDATE, NULL);
	
SELECT * FROM TBLTODO t ;

INSERT INTO TBLTODO  (SEQ, TITLE , ADDDATE, COMPLETEDATE)
		VALUES (23, 'HTML 복습하기', SYSDATE, NULL);
	
SELECT * FROM TBLTODO T;

INSERT INTO TBLTODO (SEQ, TITLE , ADDDATE, COMPLETEDATE)
		VALUES (24, 'CSS 복습하기', SYSDATE, NULL);	
	
COMMIT;

SELECT * FROM TBLADDRESSBOOK T;
SELECT * FROM TBLADDRESSBOOK ;

